// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"
)

// Defines values for PipelineSource.
const (
	PipelineSourceManual       PipelineSource = "manual"
	PipelineSourceMergeRequest PipelineSource = "merge_request"
	PipelineSourceOther        PipelineSource = "other"
	PipelineSourcePush         PipelineSource = "push"
	PipelineSourceSchedule     PipelineSource = "schedule"
	PipelineSourceTrigger      PipelineSource = "trigger"
)

// Defines values for PipelineStatus.
const (
	PipelineStatusCancelled PipelineStatus = "cancelled"
	PipelineStatusFailed    PipelineStatus = "failed"
	PipelineStatusManual    PipelineStatus = "manual"
	PipelineStatusPending   PipelineStatus = "pending"
	PipelineStatusRunning   PipelineStatus = "running"
	PipelineStatusSkipped   PipelineStatus = "skipped"
	PipelineStatusSuccess   PipelineStatus = "success"
)

// Defines values for PipelineVariableVariableType.
const (
	EnvVar PipelineVariableVariableType = "env_var"
	File   PipelineVariableVariableType = "file"
)

// Defines values for PullRequestState.
const (
	PullRequestStateClosed PullRequestState = "closed"
	PullRequestStateMerged PullRequestState = "merged"
	PullRequestStateOpen   PullRequestState = "open"
)

// Defines values for RepositoryVisibility.
const (
	RepositoryVisibilityPrivate RepositoryVisibility = "private"
	RepositoryVisibilityPublic  RepositoryVisibility = "public"
)

// Defines values for RepositoryDetailsVisibility.
const (
	RepositoryDetailsVisibilityPrivate RepositoryDetailsVisibility = "private"
	RepositoryDetailsVisibilityPublic  RepositoryDetailsVisibility = "public"
)

// Defines values for InvalidateCacheParamsEndpoint.
const (
	Branches      InvalidateCacheParamsEndpoint = "branches"
	Organizations InvalidateCacheParamsEndpoint = "organizations"
	Pipelines     InvalidateCacheParamsEndpoint = "pipelines"
	Pullrequests  InvalidateCacheParamsEndpoint = "pullrequests"
	Repositories  InvalidateCacheParamsEndpoint = "repositories"
)

// Defines values for ListPipelinesParamsStatus.
const (
	Cancelled ListPipelinesParamsStatus = "cancelled"
	Failed    ListPipelinesParamsStatus = "failed"
	Manual    ListPipelinesParamsStatus = "manual"
	Pending   ListPipelinesParamsStatus = "pending"
	Running   ListPipelinesParamsStatus = "running"
	Skipped   ListPipelinesParamsStatus = "skipped"
	Success   ListPipelinesParamsStatus = "success"
)

// Defines values for ListPullRequestsParamsState.
const (
	ListPullRequestsParamsStateAll    ListPullRequestsParamsState = "all"
	ListPullRequestsParamsStateClosed ListPullRequestsParamsState = "closed"
	ListPullRequestsParamsStateMerged ListPullRequestsParamsState = "merged"
	ListPullRequestsParamsStateOpen   ListPullRequestsParamsState = "open"
)

// Branch defines model for Branch.
type Branch struct {
	Name string `json:"name"`
}

// BranchesResponse defines model for BranchesResponse.
type BranchesResponse struct {
	Data []Branch `json:"data"`
}

// CacheInvalidationResponse defines model for CacheInvalidationResponse.
type CacheInvalidationResponse struct {
	// Endpoint The endpoint for which cache was invalidated
	Endpoint string `json:"endpoint"`

	// Message A message indicating the result of the cache invalidation
	Message string `json:"message"`
}

// Error defines model for Error.
type Error struct {
	// Code A short error code representing the type of error
	Code string `json:"code"`

	// Message A human-readable message providing more details about the error
	Message string `json:"message"`
}

// Organization defines model for Organization.
type Organization struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Id        string  `json:"id"`
	Name      string  `json:"name"`
}

// OrganizationsResponse defines model for OrganizationsResponse.
type OrganizationsResponse struct {
	Data []Organization `json:"data"`
}

// Owner defines model for Owner.
type Owner struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Id        string  `json:"id"`
	Name      string  `json:"name"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page    *int `json:"page,omitempty"`
	PerPage *int `json:"per_page,omitempty"`
	Total   int  `json:"total"`
}

// Pipeline defines model for Pipeline.
type Pipeline struct {
	CreatedAt time.Time `json:"created_at"`

	// Id Pipeline ID (string to accommodate different providers)
	Id string `json:"id"`

	// ProjectId Project/repository ID
	ProjectId *string `json:"project_id,omitempty"`

	// Ref Branch/tag ref
	Ref string `json:"ref"`

	// Sha Commit SHA
	Sha string `json:"sha"`

	// Source What triggered the pipeline
	Source *PipelineSource `json:"source,omitempty"`

	// Status Normalized pipeline status
	Status    PipelineStatus `json:"status"`
	UpdatedAt *time.Time     `json:"updated_at,omitempty"`

	// WebUrl URL to view pipeline in provider UI
	WebUrl string `json:"web_url"`
}

// PipelineSource What triggered the pipeline
type PipelineSource string

// PipelineStatus Normalized pipeline status
type PipelineStatus string

// PipelineResponse defines model for PipelineResponse.
type PipelineResponse struct {
	// Id Pipeline ID
	Id int `json:"id"`

	// Ref Branch/tag/commit used
	Ref string `json:"ref"`

	// Sha Commit SHA
	Sha *string `json:"sha,omitempty"`

	// Status Pipeline status
	Status string `json:"status"`

	// WebUrl URL to view pipeline in GitLab UI
	WebUrl string `json:"web_url"`
}

// PipelineVariable defines model for PipelineVariable.
type PipelineVariable struct {
	// Key Variable name
	Key string `json:"key"`

	// Value Variable value
	Value string `json:"value"`

	// VariableType Type of variable
	VariableType *PipelineVariableVariableType `json:"variable_type,omitempty"`
}

// PipelineVariableVariableType Type of variable
type PipelineVariableVariableType string

// PipelinesResponse defines model for PipelinesResponse.
type PipelinesResponse struct {
	Data       []Pipeline `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// PullRequest defines model for PullRequest.
type PullRequest struct {
	Author *Owner `json:"author,omitempty"`

	// CommitSha Head commit SHA of the source branch
	CommitSha *string   `json:"commit_sha,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// Description Pull request body text
	Description *string `json:"description,omitempty"`

	// Draft Whether this pull request is a draft
	Draft        *bool            `json:"draft,omitempty"`
	Id           string           `json:"id"`
	Number       int              `json:"number"`
	SourceBranch string           `json:"source_branch"`
	State        PullRequestState `json:"state"`
	TargetBranch string           `json:"target_branch"`
	Title        string           `json:"title"`
	UpdatedAt    time.Time        `json:"updated_at"`
	Url          string           `json:"url"`
}

// PullRequestState defines model for PullRequest.State.
type PullRequestState string

// PullRequestsResponse defines model for PullRequestsResponse.
type PullRequestsResponse struct {
	Data       []PullRequest `json:"data"`
	Pagination Pagination    `json:"pagination"`
}

// RepositoriesResponse defines model for RepositoriesResponse.
type RepositoriesResponse struct {
	Data []Repository `json:"data"`
}

// Repository defines model for Repository.
type Repository struct {
	DefaultBranch *string               `json:"default_branch,omitempty"`
	Description   *string               `json:"description,omitempty"`
	Id            string                `json:"id"`
	Name          string                `json:"name"`
	Owner         *string               `json:"owner,omitempty"`
	Url           *string               `json:"url,omitempty"`
	Visibility    *RepositoryVisibility `json:"visibility,omitempty"`
}

// RepositoryVisibility defines model for Repository.Visibility.
type RepositoryVisibility string

// RepositoryDetails defines model for RepositoryDetails.
type RepositoryDetails struct {
	CreatedAt     *time.Time                   `json:"created_at,omitempty"`
	DefaultBranch *string                      `json:"default_branch,omitempty"`
	Description   *string                      `json:"description,omitempty"`
	ForksCount    *int                         `json:"forks_count,omitempty"`
	HttpUrl       *string                      `json:"http_url,omitempty"`
	Id            string                       `json:"id"`
	Name          string                       `json:"name"`
	Owner         *Owner                       `json:"owner,omitempty"`
	SshUrl        *string                      `json:"ssh_url,omitempty"`
	StarsCount    *int                         `json:"stars_count,omitempty"`
	Url           *string                      `json:"url,omitempty"`
	Visibility    *RepositoryDetailsVisibility `json:"visibility,omitempty"`
}

// RepositoryDetailsVisibility defines model for RepositoryDetails.Visibility.
type RepositoryDetailsVisibility string

// GitServerParam defines model for gitServerParam.
type GitServerParam = string

// RepoNameParam defines model for repoNameParam.
type RepoNameParam = string

// RepoNameQueryParam defines model for repoNameQueryParam.
type RepoNameQueryParam = string

// RepoOwnerParam defines model for repoOwnerParam.
type RepoOwnerParam = string

// ListBranchesParams defines parameters for ListBranches.
type ListBranchesParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`

	// Owner The owner of the repository.
	Owner RepoOwnerParam `form:"owner" json:"owner"`

	// RepoName The name of the repository.
	RepoName RepoNameParam `form:"repoName" json:"repoName"`
}

// InvalidateCacheParams defines parameters for InvalidateCache.
type InvalidateCacheParams struct {
	// Endpoint The endpoint name to invalidate cache for (repositories, organizations, branches, pullrequests, pipelines)
	Endpoint InvalidateCacheParamsEndpoint `form:"endpoint" json:"endpoint"`
}

// InvalidateCacheParamsEndpoint defines parameters for InvalidateCache.
type InvalidateCacheParamsEndpoint string

// ListPipelinesParams defines parameters for ListPipelines.
type ListPipelinesParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`

	// Project Project path (e.g., "epmd-edp/temp/sk-test")
	Project string `form:"project" json:"project"`

	// Ref Filter by branch/tag ref
	Ref *string `form:"ref,omitempty" json:"ref,omitempty"`

	// Status Filter by pipeline status
	Status  *ListPipelinesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Page    *int                       `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int                       `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListPipelinesParamsStatus defines parameters for ListPipelines.
type ListPipelinesParamsStatus string

// ListPullRequestsParams defines parameters for ListPullRequests.
type ListPullRequestsParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`

	// Owner The owner of the repository.
	Owner RepoOwnerParam `form:"owner" json:"owner"`

	// RepoName The name of the repository.
	RepoName RepoNameParam `form:"repoName" json:"repoName"`

	// State Filter by state. Defaults to open.
	State   *ListPullRequestsParamsState `form:"state,omitempty" json:"state,omitempty"`
	Page    *int                         `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int                         `form:"perPage,omitempty" json:"perPage,omitempty"`
}

// ListPullRequestsParamsState defines parameters for ListPullRequests.
type ListPullRequestsParamsState string

// ListRepositoriesParams defines parameters for ListRepositories.
type ListRepositoriesParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`

	// Owner The owner of the repository.
	Owner RepoOwnerParam `form:"owner" json:"owner"`

	// RepoName The name of the repository to search for.
	RepoName *RepoNameQueryParam `form:"repoName,omitempty" json:"repoName,omitempty"`
}

// GetRepositoryParams defines parameters for GetRepository.
type GetRepositoryParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`

	// Owner The owner of the repository.
	Owner RepoOwnerParam `form:"owner" json:"owner"`

	// RepoName The name of the repository.
	RepoName RepoNameParam `form:"repoName" json:"repoName"`
}

// TriggerPipelineParams defines parameters for TriggerPipeline.
type TriggerPipelineParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`

	// Project Project path (e.g., "epmd-edp/temp/sk-test")
	Project string `form:"project" json:"project"`

	// Ref Branch/tag/commit (e.g., "main")
	Ref string `form:"ref" json:"ref"`

	// Variables JSON array of pipeline variables
	Variables *string `form:"variables,omitempty" json:"variables,omitempty"`
}

// ListUserOrganizationsParams defines parameters for ListUserOrganizations.
type ListUserOrganizationsParams struct {
	// GitServer The Git server name.
	GitServer GitServerParam `form:"gitServer" json:"gitServer"`
}
