// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"
)

// Defines values for RepositoryVisibility.
const (
	RepositoryVisibilityPrivate RepositoryVisibility = "private"
	RepositoryVisibilityPublic  RepositoryVisibility = "public"
)

// Defines values for RepositoryDetailsVisibility.
const (
	RepositoryDetailsVisibilityPrivate RepositoryDetailsVisibility = "private"
	RepositoryDetailsVisibilityPublic  RepositoryDetailsVisibility = "public"
)

// Error defines model for Error.
type Error struct {
	// Code A short error code representing the type of error
	Code string `json:"code"`

	// Message A human-readable message providing more details about the error
	Message string `json:"message"`
}

// Owner defines model for Owner.
type Owner struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Id        string  `json:"id"`
	Name      string  `json:"name"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	NextPage int `json:"next_page"`
	Page     int `json:"page"`
	PerPage  int `json:"per_page"`
	Total    int `json:"total"`
}

// RepositoriesResponse defines model for RepositoriesResponse.
type RepositoriesResponse struct {
	Data []Repository `json:"data"`
}

// Repository defines model for Repository.
type Repository struct {
	DefaultBranch *string               `json:"default_branch,omitempty"`
	Description   *string               `json:"description,omitempty"`
	Id            string                `json:"id"`
	Name          string                `json:"name"`
	Owner         *string               `json:"owner,omitempty"`
	Url           *string               `json:"url,omitempty"`
	Visibility    *RepositoryVisibility `json:"visibility,omitempty"`
}

// RepositoryVisibility defines model for Repository.Visibility.
type RepositoryVisibility string

// RepositoryDetails defines model for RepositoryDetails.
type RepositoryDetails struct {
	CreatedAt     *time.Time                   `json:"created_at,omitempty"`
	DefaultBranch *string                      `json:"default_branch,omitempty"`
	Description   *string                      `json:"description,omitempty"`
	ForksCount    *int                         `json:"forks_count,omitempty"`
	HttpUrl       *string                      `json:"http_url,omitempty"`
	Id            string                       `json:"id"`
	Name          string                       `json:"name"`
	Owner         *Owner                       `json:"owner,omitempty"`
	SshUrl        *string                      `json:"ssh_url,omitempty"`
	StarsCount    *int                         `json:"stars_count,omitempty"`
	Url           *string                      `json:"url,omitempty"`
	Visibility    *RepositoryDetailsVisibility `json:"visibility,omitempty"`
}

// RepositoryDetailsVisibility defines model for RepositoryDetails.Visibility.
type RepositoryDetailsVisibility string

// GitServerParam defines model for gitServerParam.
type GitServerParam = string

// RepoNameParam defines model for repoNameParam.
type RepoNameParam = string

// RepoNameQueryParam defines model for repoNameQueryParam.
type RepoNameQueryParam = string

// RepoOwnerParam defines model for repoOwnerParam.
type RepoOwnerParam = string

// ListBitbucketRepositoriesParams defines parameters for ListBitbucketRepositories.
type ListBitbucketRepositoriesParams struct {
	// RepoName The name of the repository to search for.
	RepoName *RepoNameQueryParam `form:"repoName,omitempty" json:"repoName,omitempty"`
}

// ListGitHubRepositoriesParams defines parameters for ListGitHubRepositories.
type ListGitHubRepositoriesParams struct {
	// RepoName The name of the repository to search for.
	RepoName *RepoNameQueryParam `form:"repoName,omitempty" json:"repoName,omitempty"`
}

// ListGitlabRepositoriesParams defines parameters for ListGitlabRepositories.
type ListGitlabRepositoriesParams struct {
	// RepoName The name of the repository to search for.
	RepoName *RepoNameQueryParam `form:"repoName,omitempty" json:"repoName,omitempty"`
}
