openapi: "3.0.0"
info:
  version: 1.0.0
  title: GitFusion API server
paths:
  /api/v1/providers/github/{git-server}/{org}/repositories:
    get:
      summary: List organization repositories
      operationId: listGitHubRepositories
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/orgParam'
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/perPageParam'
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoriesResponse'
        '400':
          description: Bad request due to invalid parameters or missing fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/providers/github/{git-server}/repositories/{owner}/{repo}:
    get:
      summary: Get detailed information for a specific GitHub repository
      operationId: getGitHubRepository
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/ownerParam'
        - $ref: '#/components/parameters/repoParam'
      responses:
        '200':
          description: Detailed information about a repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '404':
          description: Git server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Something went wrong with the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/providers/gitlab/{git-server}/{org}/repositories:
    get:
      summary: List repositories
      operationId: listGitlabRepositories
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/orgParam'
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/perPageParam'
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoriesResponse'
        '400':
          description: Something went wrong with the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/providers/gitlab/{git-server}/repositories/{owner}/{repo}:
    get:
      summary: Get detailed information for a specific Gitlab repository
      operationId: getGitlabRepository
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/ownerParam'
        - $ref: '#/components/parameters/repoParam'
      responses:
        '200':
          description: Detailed information about a repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '404':
          description: Git server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Something went wrong with the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/providers/bitbucket/{git-server}/{org}/repositories:
    get:
      summary: List repositories
      operationId: listBitbucketRepositories
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/orgParam'
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/perPageParam'
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoriesResponse'
        '400':
          description: Bad request due to invalid parameters or missing fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/providers/bitbucket/{git-server}/repositories/{owner}/{repo}:
    get:
      summary: Get detailed information for a specific Bitbucket repository
      operationId: getBitbucketRepository
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/ownerParam'
        - $ref: '#/components/parameters/repoParam'
      responses:
        '200':
          description: Detailed information about a repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '404':
          description: Git server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Something went wrong with the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    pageParam:
      name: page
      in: query
      required: false
      description: The page number for pagination.
      schema:
        type: integer
    perPageParam:
      name: per_page
      in: query
      required: false
      description: The number of items per page for pagination.
      schema:
        type: integer
    gitServerParam:
      name: git-server
      in: path
      required: true
      description: The Git server name.
      schema:
        type: string
    orgParam:
      name: org
      in: path
      required: true
      description: The organization name in the Git server.
      schema:
        type: string
    ownerParam:
      name: owner
      in: path
      required: true
      description: The owner of the repository.
      schema:
        type: string
    repoParam:
      name: repo
      in: path
      required: true
      description: The name of the repository.
      schema:
        type: string
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        avatar_url:
          type: string
      required:
        - id
        - name
    Repository:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        owner:
          type: string
        visibility:
          type: string
          enum: [public, private]
        default_branch:
          type: string
      required:
        - id
        - name
    Pagination:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
        next_page:
          type: integer
      required:
        - total
        - page
        - per_page
        - next_page
    RepositoryDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        ssh_url:
          type: string
        http_url:
          type: string
        owner:
          $ref: '#/components/schemas/Owner'
        visibility:
          type: string
          enum: [public, private]
        created_at:
          type: string
          format: date-time
        default_branch:
          type: string
        forks_count:
          type: integer
        stars_count:
          type: integer
      required:
        - id
        - name
    RepositoriesResponse:
      type: object
      properties:
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/Repository'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - repositories
        - pagination
    Error:
      type: object
      properties:
        code:
          type: string
          description: A short error code representing the type of error
        message:
          type: string
          description: A human-readable message providing more details about the error
      required:
        - code
        - message
