openapi: "3.0.0"
info:
  version: 1.0.0
  title: GitFusion API server
paths:
  /api/v1/repositories:
    get:
      summary: List repositories
      operationId: listRepositories
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/repoOwnerParam'
        - $ref: '#/components/parameters/repoNameQueryParam'
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoriesResponse'
        '400':
          description: Bad request due to invalid parameters or missing fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/repository:
    get:
      summary: Get detailed information for a specific repository
      operationId: getRepository
      tags:
        - Repositories
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/repoOwnerParam'
        - $ref: '#/components/parameters/repoNameParam'
      responses:
        '200':
          description: Detailed information about a repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '404':
          description: Git server not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Something went wrong with the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/user/organizations:
    get:
      summary: List organizations for the authenticated user
      operationId: listUserOrganizations
      tags:
        - Organizations
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
      responses:
        '200':
          description: A list of organizations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationsResponse'
        '400':
          description: Bad request due to invalid parameters or missing fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/branches:
    get:
      summary: List branches for a repository
      operationId: listBranches
      tags:
        - Branches
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/repoOwnerParam'
        - $ref: '#/components/parameters/repoNameParam'
      responses:
        '200':
          description: A list of branches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BranchesResponse'
        '400':
          description: Bad request due to invalid parameters or missing fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/trigger-pipeline:
    post:
      summary: Trigger a CI/CD pipeline
      operationId: triggerPipeline
      tags:
        - Pipeline
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - name: project
          in: query
          required: true
          description: Project path (e.g., "epmd-edp/temp/sk-test")
          schema:
            type: string
        - name: ref
          in: query
          required: true
          description: Branch/tag/commit (e.g., "main")
          schema:
            type: string
        - name: variables
          in: query
          required: false
          description: JSON array of pipeline variables
          schema:
            type: string
      responses:
        '201':
          description: Pipeline created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PipelineResponse'
        '400':
          description: Bad request due to invalid parameters or variables format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: GitServer, project, or ref not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/pull-requests:
    get:
      summary: List pull/merge requests for a repository
      operationId: listPullRequests
      tags:
        - PullRequests
      parameters:
        - $ref: '#/components/parameters/gitServerParam'
        - $ref: '#/components/parameters/repoOwnerParam'
        - $ref: '#/components/parameters/repoNameParam'
        - name: state
          in: query
          required: false
          description: Filter by state. Defaults to open.
          schema:
            type: string
            enum: [open, closed, merged, all]
            default: open
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: A list of pull/merge requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullRequestsResponse'
        '400':
          description: Bad request due to invalid parameters or missing fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized access due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Repository or git server not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/cache/invalidate:
    delete:
      summary: Invalidate cache for a specific endpoint
      operationId: invalidateCache
      tags:
        - Cache
      parameters:
        - name: endpoint
          in: query
          required: true
          description: The endpoint name to invalidate cache for (repositories, organizations, branches, pullrequests)
          schema:
            type: string
            enum: [repositories, organizations, branches, pullrequests]
      responses:
        '200':
          description: Cache invalidated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheInvalidationResponse'
        '400':
          description: Bad request due to invalid parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    repoNameQueryParam:
      name: repoName
      in: query
      required: false
      description: The name of the repository to search for.
      schema:
        type: string
    gitServerParam:
      name: gitServer
      in: query
      required: true
      description: The Git server name.
      schema:
        type: string
    repoOwnerParam:
      name: owner
      in: query
      required: true
      description: The owner of the repository.
      schema:
        type: string
    repoNameParam:
      name: repoName
      in: query
      required: true
      description: The name of the repository.
      schema:
        type: string
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        avatar_url:
          type: string
      required:
        - id
        - name
    Repository:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        owner:
          type: string
        visibility:
          type: string
          enum: [public, private]
        default_branch:
          type: string
      required:
        - id
        - name
    Pagination:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
      required:
        - total
    RepositoryDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        ssh_url:
          type: string
        http_url:
          type: string
        owner:
          $ref: '#/components/schemas/Owner'
        visibility:
          type: string
          enum: [public, private]
        created_at:
          type: string
          format: date-time
        default_branch:
          type: string
        forks_count:
          type: integer
        stars_count:
          type: integer
      required:
        - id
        - name
    RepositoriesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Repository'
      required:
        - data
    Error:
      type: object
      properties:
        code:
          type: string
          description: A short error code representing the type of error
        message:
          type: string
          description: A human-readable message providing more details about the error
      required:
        - code
        - message
    OrganizationsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
      required:
        - data
    Organization:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        avatar_url:
          type: string
      required:
        - id
        - name
    Branch:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    BranchesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
      required:
        - data
    CacheInvalidationResponse:
      type: object
      properties:
        message:
          type: string
          description: A message indicating the result of the cache invalidation
        endpoint:
          type: string
          description: The endpoint for which cache was invalidated
      required:
        - message
        - endpoint
    PipelineVariable:
      type: object
      properties:
        key:
          type: string
          description: Variable name
        value:
          type: string
          description: Variable value
        variable_type:
          type: string
          enum: [env_var, file]
          description: Type of variable
      required:
        - key
        - value
    PullRequest:
      type: object
      properties:
        id:
          type: string
        number:
          type: integer
        title:
          type: string
        state:
          type: string
          enum: [open, closed, merged]
        author:
          $ref: '#/components/schemas/Owner'
        source_branch:
          type: string
        target_branch:
          type: string
        url:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        description:
          type: string
          description: Pull request body text
        draft:
          type: boolean
          description: Whether this pull request is a draft
        commit_sha:
          type: string
          description: Head commit SHA of the source branch
      required:
        - id
        - number
        - title
        - state
        - source_branch
        - target_branch
        - url
        - created_at
        - updated_at
    PullRequestsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PullRequest'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - data
        - pagination
    PipelineResponse:
      type: object
      properties:
        id:
          type: integer
          description: Pipeline ID
        web_url:
          type: string
          description: URL to view pipeline in GitLab UI
        status:
          type: string
          description: Pipeline status
        ref:
          type: string
          description: Branch/tag/commit used
        sha:
          type: string
          description: Commit SHA
      required:
        - id
        - web_url
        - status
        - ref
