apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gitfusion.fullname" . }}-role
  labels:
    {{- include "gitfusion.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - watch
      - list
    resources:
      - secrets
  - apiGroups:
      - v2.edp.epam.com
    verbs:
      - get
      - watch
      - list
    resources:
      - gitservers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gitfusion.fullname" . }}-rolebinding
  labels:
    {{- include "gitfusion.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gitfusion.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "gitfusion.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

